#!/bin/bash
#
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT. PLEASE REFER TO ORIGINAL SCRIPT.
# THIS FILE IS A TEMPLATE AND IT SHOULD NOT BE DEPLOYED TO PRODUCTION!
#
#SBATCH --partition={{PARTITION_NAME}}
#SBATCH --job-name={{JOB_NAME}}
#SBATCH --output={{LOG_FILE}}
{{GIVEN_NODE}}

### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodes={{NUM_NODES}}
#SBATCH --exclusive

### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task={{NUM_GPUS_PER_NODE}}

# Load modules or conda environment
{{LOAD_ENV}}

################# DO NOT CHANGE THINGS HERE UNLESS YOU KNOW WHAT YOU ARE DOING ###############
redis_password=$(uuidgen)
export redis_password

nodes=$(scontrol show hostnames $SLURM_JOB_NODELIST) # get the node names
nodes_array=($nodes)

node_1=${nodes_array[0]}
ip=$(srun --nodes=1 --ntasks=1 -w $node_1 hostname --ip-address) # make redis-address

if [[ $ip == *" "* ]]; then
  IFS=' ' read -ra ADDR <<<"$ip"
  if [[ ${#ADDR[0]} > 16 ]]; then
    ip=${ADDR[1]}
  else
    ip=${ADDR[0]}
  fi
  echo "IPV6 address detected: IPV4 address is $ip"
fi

port={{PORT_NUMBER}}
IP_HEAD=$ip:$port
export IP_HEAD

echo "IP Head: $IP_HEAD"

export RAY_ADDRESS="ray://$IP_HEAD"

echo "Ray address: $RAY_ADDRESS"

echo "STARTING HEAD at $node_1"
# srun --nodes=1 --ntasks=1 -w $node_1 start-head.sh $ip $redis_password &
srun --nodes=1 --ntasks=1 --nodelist $node_1 \
  ray start --head --node-ip-address=$ip --port=$port --redis-password=$redis_password --block &
sleep 30

# RJP: this allocates one worker per node. We want to do this per task instead.
# RJP: try using $SLURM_NTASKS instead of $SLURM_JOB_NUM_NODES.
worker_num=$(($SLURM_JOB_NUM_NODES - 1)) # number of nodes other than the head node
for ((i = 1; i <= $worker_num; i++)); do
  node_i=${nodes_array[$i]}
  echo "Starting worker $i at $node_i"
  srun --nodes=1 --ntasks=1 --nodelist $node_i ray start --address $IP_HEAD --redis-password=$redis_password --block &
  sleep 5
done
##############################################################################################

# Command can connect to Ray using $RAY_ADDRESS
{{COMMAND}} {{COMMAND_SUFFIX}}
