#
# String constants
#
CLUSTER_NONE  = 'serial'  # no cluster; just run fields serially
CLUSTER_LOCAL = 'local'
CLUSTER_SLURM = 'slurm'
CLUSTER_TYPES = (CLUSTER_NONE, CLUSTER_SLURM, CLUSTER_LOCAL)

SIMPLE_RESULT = 'simple'
DETAILED_RESULT = 'detailed'
ERROR_RESULT = 'error'
DEFAULT_RESULT_TYPE = SIMPLE_RESULT
USER_RESULT_TYPES = (SIMPLE_RESULT, DETAILED_RESULT) # used by argument parser
ALL_RESULT_TYPES  = (SIMPLE_RESULT, DETAILED_RESULT, ERROR_RESULT)
